import type { Project, ToolAdapterDefinition, ToolDefinition } from "./types";

export const defaultToolAdapters: ToolAdapterDefinition[] = [
  {
    id: "codex",
    name: "Codex CLI",
    shortName: "Codex",
    description: "OpenAI coding agent CLI.",
    category: "coding-agent",
    defaultCommand: "codex",
    detectionArgs: [["--version"], ["-V"]],
    installCommandPreview: "npm install -g @openai/codex",
    homepageUrl: "https://github.com/openai/codex",
    iconKey: "codex",
    tags: ["openai", "coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "claude",
    name: "Claude Code / Claude CLI",
    shortName: "Claude",
    description: "Claude command-line coding assistant.",
    category: "coding-agent",
    defaultCommand: "claude",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "See official Claude Code installation instructions.",
    iconKey: "claude",
    tags: ["anthropic", "coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    shortName: "OpenCode",
    description: "OpenCode-compatible AI coding CLI.",
    category: "coding-agent",
    defaultCommand: "opencode",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "opencode",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "openclaude",
    name: "OpenClaude",
    shortName: "OpenClaude",
    description: "OpenClaude-compatible AI coding CLI.",
    category: "coding-agent",
    defaultCommand: "openclaude",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "openclaude",
    tags: ["claude", "coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "grok",
    name: "Grok CLI",
    shortName: "Grok",
    description: "Grok-compatible AI coding CLI.",
    category: "coding-agent",
    defaultCommand: "grok",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "grok",
    tags: ["grok", "coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "codebuff",
    name: "Codebuff",
    shortName: "Codebuff",
    description: "Codebuff-compatible coding agent CLI.",
    category: "coding-agent",
    defaultCommand: "codebuff",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "codebuff",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "freebuff",
    name: "Freebuff",
    shortName: "Freebuff",
    description: "Freebuff-compatible coding agent CLI.",
    category: "coding-agent",
    defaultCommand: "freebuff",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "freebuff",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "aider",
    name: "Aider",
    shortName: "Aider",
    description: "Aider command-line AI pair programming assistant.",
    category: "coding-agent",
    defaultCommand: "aider",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "pipx install aider-chat",
    homepageUrl: "https://aider.chat/",
    iconKey: "aider",
    tags: ["coding", "agent", "python"],
    isBuiltIn: true,
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    shortName: "Gemini",
    description: "Gemini-compatible assistant CLI profile.",
    category: "assistant-cli",
    defaultCommand: "gemini",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "gemini",
    tags: ["google", "assistant", "agent"],
    isBuiltIn: true,
  },
  {
    id: "kilo",
    name: "Kilo CLI",
    shortName: "Kilo",
    description: "Kilo-compatible coding agent CLI profile.",
    category: "coding-agent",
    defaultCommand: "kilo",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "kilo",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "antigravity",
    name: "Antigravity CLI",
    shortName: "Antigravity",
    description: "Antigravity-compatible coding agent CLI profile.",
    category: "coding-agent",
    defaultCommand: "antigravity",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "antigravity",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "cursor",
    name: "Cursor CLI",
    shortName: "Cursor",
    description: "Cursor-compatible command-line agent profile.",
    category: "assistant-cli",
    defaultCommand: "cursor",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "cursor",
    tags: ["cursor", "assistant", "agent"],
    isBuiltIn: true,
  },
  {
    id: "qwen",
    name: "Qwen Code",
    shortName: "Qwen",
    description: "Qwen Code-compatible CLI agent profile.",
    category: "coding-agent",
    defaultCommand: "qwen",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "qwen",
    tags: ["qwen", "coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "goose",
    name: "Goose",
    shortName: "Goose",
    description: "Goose-compatible local agent CLI profile.",
    category: "coding-agent",
    defaultCommand: "goose",
    detectionArgs: [["--version"], ["-v"]],
    installCommandPreview: "Configure install command manually.",
    iconKey: "goose",
    tags: ["coding", "agent"],
    isBuiltIn: true,
  },
  {
    id: "generic",
    name: "Generic Custom Agent",
    shortName: "Custom",
    description: "User-configured local CLI agent profile.",
    category: "custom",
    defaultCommand: "custom-tool",
    detectionArgs: [
      ["--version"],
      ["-v"],
      ["-Command", "$PSVersionTable.PSVersion.ToString()"],
      ["/c", "ver"],
    ],
    installCommandPreview: "Configure manually.",
    iconKey: "generic",
    tags: ["custom", "local"],
    isBuiltIn: true,
  },
];

export const mockTools: ToolDefinition[] = defaultToolAdapters.map((definition) => ({
  ...definition,
  status: definition.id === "generic" ? "needs_setup" : "not_checked",
  installCommand: definition.installCommandPreview,
}));

export const mockProject: Project = {
  id: "budget-cargo",
  name: "budget-cargo",
  path: "C:\\Users\\mozay\\Projects\\budget-cargo",
  files: [
    {
      name: "src",
      path: "src",
      relativePath: "src",
      nodeType: "directory",
      children: [
        {
          name: "api",
          path: "src/api",
          relativePath: "src/api",
          nodeType: "directory",
          children: [],
        },
        {
          name: "components",
          path: "src/components",
          relativePath: "src/components",
          nodeType: "directory",
          children: [],
        },
        {
          name: "pages",
          path: "src/pages",
          relativePath: "src/pages",
          nodeType: "directory",
          children: [],
        },
      ],
    },
    {
      name: "package.json",
      path: "package.json",
      relativePath: "package.json",
      nodeType: "file",
      extension: "json",
      sizeBytes: 1184,
    },
    {
      name: "README.md",
      path: "README.md",
      relativePath: "README.md",
      nodeType: "file",
      extension: "md",
      sizeBytes: 2048,
    },
    {
      name: "tailwind.config.js",
      path: "tailwind.config.js",
      relativePath: "tailwind.config.js",
      nodeType: "file",
      extension: "js",
      sizeBytes: 720,
    },
  ],
  totalFiles: 3,
  totalDirectories: 4,
  ignoredCount: 0,
  truncated: false,
};
